## /boot/extlinux/extlinux.conf
default custom
menu title U-Boot menu
prompt 1
timeout 10

label custom
	menu label Custom Kernel 6.1.115+ MIPI DBI
	linux /boot/vmlinuz-6.1.115-8-rk2501
	initrd /boot/initrd.img-6.1.115-8-rk2501
	fdt /boot/dtbo/rk3399-rock-4se-mipidbi.dtb
	append root=UUID=c73acf2e-f0f7-4122-a523-d540df12fc5a console=ttyFIQ0,1500000n8 quiet splash loglevel=4 rw earlycon consoleblank=0 console=tty1 coherent_pool=2M irqchip.gicv3_pseudo_nmi=0 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory swapaccount=1 kasan=off

label l0
	menu label Debian GNU/Linux 12 (bookworm) 6.1.115-8-rk2501 (stock fallback)
	linux /boot/vmlinuz-6.1.115-8-rk2501
	initrd /boot/initrd.img-6.1.115-8-rk2501
	fdtdir /usr/lib/linux-image-6.1.115-8-rk2501/
	append root=UUID=c73acf2e-f0f7-4122-a523-d540df12fc5a console=ttyFIQ0,1500000n8 quiet splash loglevel=4 rw earlycon consoleblank=0 console=tty1 coherent_pool=2M irqchip.gicv3_pseudo_nmi=0 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory swapaccount=1 kasan=off
